[features]
seeds = false
skip-lint = false

[programs.devnet]
agentvault = "HvWGEDbnRCVThyCNwUVpFRfWsHx2aqT9Ttotr4QovGCF"

[programs.localnet]
agentvault = "HvWGEDbnRCVThyCNwUVpFRfWsHx2aqT9Ttotr4QovGCF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
