/**
 * Anchor integration test suite. Runs via `anchor test` once the program is
 * deployed to localnet/devnet, or via `pnpm exec mocha` against a running
 * solana-bankrun instance.
 *
 * Covers the 13 cases listed in docs/01_SOLANA_PROGRAM.md §8.
 */
import * as anchor from "@coral-xyz/anchor";
import { BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram, LAMPORTS_PER_SOL } from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import { assert, expect } from "chai";
import crypto from "node:crypto";

// Generated by `anchor build` once the program is built. Until then the test
// suite reads the JSON IDL from the workspace's shared types package.
import { AGENTVAULT_IDL } from "@agentvault/types";

const TITLE = "Anchor Framework Senior Dev";
const TAGS = ["anchor", "solana", "rust", "pda"];
const ARWEAVE_TX = "a".repeat(43);
const MODEL_ID = "qwen2.5-7b-instruct";
const PRICE_USDC = new BN(25_000_000);
const SANDBOX_PRICE_USDC = new BN(50_000);
const QUANT_SEED = new BN(42);
const BITS = 35;
const SEQ_LEN = 4096;

function randomHash(): Buffer {
  return crypto.randomBytes(32);
}

function findConfigPda(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from("config")], programId);
}
function findListingPda(seller: PublicKey, hash: Buffer, programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("listing"), seller.toBuffer(), hash],
    programId,
  );
}
function findLicensePda(buyer: PublicKey, listing: PublicKey, programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("license"), buyer.toBuffer(), listing.toBuffer()],
    programId,
  );
}
function findSandboxPda(buyer: PublicKey, listing: PublicKey, programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("sandbox"), buyer.toBuffer(), listing.toBuffer()],
    programId,
  );
}
function findDecisionPda(agent: PublicKey, ts: BN, programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("decision"), agent.toBuffer(), ts.toArrayLike(Buffer, "le", 8)],
    programId,
  );
}

describe("agentvault", () => {
  // anchor test injects ANCHOR_PROVIDER_URL + ANCHOR_WALLET; AnchorProvider.env()
  // picks them up.
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program: any = new (anchor.Program as any)(AGENTVAULT_IDL, provider);
  const programId: PublicKey = program.programId;
  const authority = provider.wallet as anchor.Wallet;

  let usdcMint: PublicKey;
  let treasury: Keypair;
  let configPda: PublicKey;

  before(async () => {
    treasury = Keypair.generate();
    // Fund the treasury so it can own an ATA without rent issues.
    const sig = await provider.connection.requestAirdrop(treasury.publicKey, LAMPORTS_PER_SOL);
    await provider.connection.confirmTransaction(sig);

    usdcMint = await createMint(
      provider.connection,
      authority.payer,
      authority.publicKey,
      null,
      6,
    );

    [configPda] = findConfigPda(programId);
  });

  // ─── Test 1: initialize platform; second init fails ───
  it("initializes the platform", async () => {
    await program.methods
      .initializePlatform(treasury.publicKey, usdcMint, 1000)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const cfg = await (program.account as any).platformConfig.fetch(configPda);
    expect(cfg.treasury.toBase58()).to.equal(treasury.publicKey.toBase58());
    expect(cfg.usdcMint.toBase58()).to.equal(usdcMint.toBase58());
    expect(cfg.platformFeeBps).to.equal(1000);
    expect(cfg.paused).to.equal(false);
  });

  it("rejects double init", async () => {
    try {
      await program.methods
        .initializePlatform(treasury.publicKey, usdcMint, 1000)
        .accounts({
          authority: authority.publicKey,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
      assert.fail("expected double init to throw");
    } catch (e: any) {
      // Anchor reports `already in use` for the existing PDA.
      expect(String(e)).to.match(/already in use|0x0/i);
    }
  });

  // ─── Test 2: list_memory: success and validation failures ───
  it("creates a listing", async () => {
    const seller = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);

    await program.methods
      .listMemory(
        ARWEAVE_TX,
        Array.from(hash),
        MODEL_ID,
        QUANT_SEED,
        BITS,
        SEQ_LEN,
        PRICE_USDC,
        SANDBOX_PRICE_USDC,
        TITLE,
        TAGS,
      )
      .accounts({
        seller: seller.publicKey,
        config: configPda,
        listing: listingPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([seller])
      .rpc();

    const listing = await (program.account as any).memoryListing.fetch(listingPda);
    expect(listing.title).to.equal(TITLE);
    expect(listing.active).to.equal(true);
    expect(listing.tags).to.deep.equal(TAGS);
  });

  it("rejects listing with too many tags", async () => {
    const seller = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);
    const tooMany = Array.from({ length: 11 }, (_, i) => `tag${i}`);

    try {
      await program.methods
        .listMemory(ARWEAVE_TX, Array.from(hash), MODEL_ID, QUANT_SEED, BITS, SEQ_LEN, PRICE_USDC, SANDBOX_PRICE_USDC, TITLE, tooMany)
        .accounts({ seller: seller.publicKey, config: configPda, listing: listingPda, systemProgram: SystemProgram.programId })
        .signers([seller])
        .rpc();
      assert.fail("expected too-many-tags error");
    } catch (e: any) {
      expect(String(e)).to.match(/TooManyTags/);
    }
  });

  it("rejects listing with bad arweave_tx length", async () => {
    const seller = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);

    try {
      await program.methods
        .listMemory("short", Array.from(hash), MODEL_ID, QUANT_SEED, BITS, SEQ_LEN, PRICE_USDC, SANDBOX_PRICE_USDC, TITLE, TAGS)
        .accounts({ seller: seller.publicKey, config: configPda, listing: listingPda, systemProgram: SystemProgram.programId })
        .signers([seller])
        .rpc();
      assert.fail("expected InvalidArweaveTx");
    } catch (e: any) {
      expect(String(e)).to.match(/InvalidArweaveTx/);
    }
  });

  it("rejects listing with invalid quantization", async () => {
    const seller = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);

    try {
      await program.methods
        .listMemory(ARWEAVE_TX, Array.from(hash), MODEL_ID, QUANT_SEED, 99, SEQ_LEN, PRICE_USDC, SANDBOX_PRICE_USDC, TITLE, TAGS)
        .accounts({ seller: seller.publicKey, config: configPda, listing: listingPda, systemProgram: SystemProgram.programId })
        .signers([seller])
        .rpc();
      assert.fail("expected InvalidQuantization");
    } catch (e: any) {
      expect(String(e)).to.match(/InvalidQuantization/);
    }
  });

  // ─── Test 3-5: buy_memory ───
  it("buy_memory transfers USDC 90/10 and creates license", async () => {
    const seller = await fundedKeypair(provider);
    const buyer = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);
    const [licensePda] = findLicensePda(buyer.publicKey, listingPda, programId);

    await createListingFor(program, configPda, seller, hash, listingPda);

    const buyerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, buyer.publicKey);
    const sellerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, seller.publicKey);
    const treasuryAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, treasury.publicKey);

    await mintTo(provider.connection, authority.payer, usdcMint, buyerAta, authority.publicKey, 100_000_000);

    await program.methods
      .buyMemory()
      .accounts({
        buyer: buyer.publicKey,
        config: configPda,
        listing: listingPda,
        license: licensePda,
        usdcMint,
        buyerUsdcAta: buyerAta,
        sellerUsdcAta: sellerAta,
        treasuryUsdcAta: treasuryAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    const sellerBalance = await provider.connection.getTokenAccountBalance(sellerAta);
    const treasuryBalance = await provider.connection.getTokenAccountBalance(treasuryAta);
    expect(Number(sellerBalance.value.amount)).to.equal(22_500_000); // 90%
    expect(Number(treasuryBalance.value.amount)).to.equal(2_500_000); // 10%

    const license = await (program.account as any).memoryLicense.fetch(licensePda);
    expect(license.buyer.toBase58()).to.equal(buyer.publicKey.toBase58());
    expect(license.listing.toBase58()).to.equal(listingPda.toBase58());

    const updatedListing = await (program.account as any).memoryListing.fetch(listingPda);
    expect(Number(updatedListing.purchases)).to.equal(1);
  });

  it("buy_memory fails on inactive listing", async () => {
    const seller = await fundedKeypair(provider);
    const buyer = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);
    const [licensePda] = findLicensePda(buyer.publicKey, listingPda, programId);

    await createListingFor(program, configPda, seller, hash, listingPda);
    await program.methods
      .delistMemory()
      .accounts({ seller: seller.publicKey, listing: listingPda })
      .signers([seller])
      .rpc();

    const buyerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, buyer.publicKey);
    const sellerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, seller.publicKey);
    const treasuryAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, treasury.publicKey).catch(() => null);

    try {
      await program.methods
        .buyMemory()
        .accounts({
          buyer: buyer.publicKey,
          config: configPda,
          listing: listingPda,
          license: licensePda,
          usdcMint,
          buyerUsdcAta: buyerAta,
          sellerUsdcAta: sellerAta,
          treasuryUsdcAta: treasuryAta!,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
      assert.fail("expected ListingInactive");
    } catch (e: any) {
      expect(String(e)).to.match(/ListingInactive/);
    }
  });

  // ─── Test 6-7: sandbox access ───
  it("buy_sandbox_access creates correct expiry/queries", async () => {
    const seller = await fundedKeypair(provider);
    const buyer = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);
    const [sandboxPda] = findSandboxPda(buyer.publicKey, listingPda, programId);

    await createListingFor(program, configPda, seller, hash, listingPda);

    const buyerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, buyer.publicKey);
    const sellerAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, seller.publicKey);
    const treasuryAta = await createAssociatedTokenAccount(provider.connection, authority.payer, usdcMint, treasury.publicKey).catch(() => null);

    await mintTo(provider.connection, authority.payer, usdcMint, buyerAta, authority.publicKey, 1_000_000);

    await program.methods
      .buySandboxAccess()
      .accounts({
        buyer: buyer.publicKey,
        config: configPda,
        listing: listingPda,
        sandbox: sandboxPda,
        usdcMint,
        buyerUsdcAta: buyerAta,
        sellerUsdcAta: sellerAta,
        treasuryUsdcAta: treasuryAta!,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    const sandbox = await (program.account as any).sandboxAccess.fetch(sandboxPda);
    expect(sandbox.queriesRemaining).to.equal(5);
    expect(sandbox.expiresAt.toNumber()).to.be.greaterThan(Math.floor(Date.now() / 1000));
  });

  // ─── Test 8: delist authorization ───
  it("delist rejects non-seller", async () => {
    const seller = await fundedKeypair(provider);
    const intruder = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);

    await createListingFor(program, configPda, seller, hash, listingPda);

    try {
      await program.methods
        .delistMemory()
        .accounts({ seller: intruder.publicKey, listing: listingPda })
        .signers([intruder])
        .rpc();
      assert.fail("expected Unauthorized");
    } catch (e: any) {
      expect(String(e)).to.match(/Unauthorized/);
    }
  });

  // ─── Test 10-11: anchor_decision ───
  it("anchor_decision creates a DecisionRecord", async () => {
    const signer = await fundedKeypair(provider);
    const ctxHash = randomHash();
    const ts = new BN(Math.floor(Date.now() / 1000));
    const [decisionPda] = findDecisionPda(signer.publicKey, ts, programId);

    await program.methods
      .anchorDecision(
        signer.publicKey,
        "trade",
        Array.from(ctxHash),
        ARWEAVE_TX,
        Buffer.from(JSON.stringify({ side: "buy", asset: "USDC" })),
        ts,
      )
      .accounts({ signer: signer.publicKey, decision: decisionPda, systemProgram: SystemProgram.programId })
      .signers([signer])
      .rpc();

    const dec = await (program.account as any).decisionRecord.fetch(decisionPda);
    expect(dec.decisionType).to.equal("trade");
    expect(dec.timestamp.toNumber()).to.equal(ts.toNumber());
  });

  it("anchor_decision rejects oversized data", async () => {
    const signer = await fundedKeypair(provider);
    const ctxHash = randomHash();
    const ts = new BN(Math.floor(Date.now() / 1000) + 1);
    const [decisionPda] = findDecisionPda(signer.publicKey, ts, programId);

    const tooBig = Buffer.alloc(257);
    try {
      await program.methods
        .anchorDecision(signer.publicKey, "trade", Array.from(ctxHash), ARWEAVE_TX, tooBig, ts)
        .accounts({ signer: signer.publicKey, decision: decisionPda, systemProgram: SystemProgram.programId })
        .signers([signer])
        .rpc();
      assert.fail("expected DecisionDataTooLarge");
    } catch (e: any) {
      expect(String(e)).to.match(/DecisionDataTooLarge/);
    }
  });

  // ─── Test 12: update price authorization ───
  it("update_listing_price rejects non-seller", async () => {
    const seller = await fundedKeypair(provider);
    const intruder = await fundedKeypair(provider);
    const hash = randomHash();
    const [listingPda] = findListingPda(seller.publicKey, hash, programId);

    await createListingFor(program, configPda, seller, hash, listingPda);

    try {
      await program.methods
        .updateListingPrice(new BN(50_000_000), new BN(100_000))
        .accounts({ seller: intruder.publicKey, listing: listingPda })
        .signers([intruder])
        .rpc();
      assert.fail("expected Unauthorized");
    } catch (e: any) {
      expect(String(e)).to.match(/Unauthorized/);
    }
  });
});

// ─── Helpers ───

async function fundedKeypair(provider: anchor.AnchorProvider, lamports = LAMPORTS_PER_SOL): Promise<Keypair> {
  const kp = Keypair.generate();
  const sig = await provider.connection.requestAirdrop(kp.publicKey, lamports);
  await provider.connection.confirmTransaction(sig);
  return kp;
}

async function createListingFor(
  program: any,
  configPda: PublicKey,
  seller: Keypair,
  hash: Buffer,
  listingPda: PublicKey,
): Promise<void> {
  await program.methods
    .listMemory(
      ARWEAVE_TX,
      Array.from(hash),
      MODEL_ID,
      QUANT_SEED,
      BITS,
      SEQ_LEN,
      PRICE_USDC,
      SANDBOX_PRICE_USDC,
      TITLE,
      TAGS,
    )
    .accounts({
      seller: seller.publicKey,
      config: configPda,
      listing: listingPda,
      systemProgram: SystemProgram.programId,
    })
    .signers([seller])
    .rpc();
}
